### ISSUE TITLE
sponsors

### ISSUE THREAD

**Issue by magnum** [WEBdeBS/nodejsconf2023#16]
patformatic
![slack-imgs](https://user-images.githubusercontent.com/9384/236405325-d0e583ec-dcaa-418c-8961-ec6e5b8efea3.png)

waiting for "the native web" one 

cc @cirpo @fgandellini

**Comment by magnum** [comment]
message from golo

> Hey there,
> sorry for being late, I was on the road the last days.
>So, now, here we go…
>Please find our logo attached to this mail as SVG, with a transparent background as you asked for, one time with a bright, and one time with a dark font – depending on whether you want to put it to a light or a dark background.
>
> We've intentionally didn’t cut them, since we didn’t know which paddings you may need or want.
>
> The link is https://www.thenativeweb.io/
> Is there anything else you need?
> Cheers,
> Golo
>
> --
> golo roden | cto and managing director
> the native web gmbh
>
> paul-ehrlich-straße 7 | 79106 freiburg im breisgau | germany
> 
> [golo.roden@thenativeweb.io](mailto:golo.roden@thenativeweb.io) | https://www.thenativeweb.io/
> registry court | freiburg im breisgau | germany
> commercial register | hrb 709303
> managing directors | susanna roden, golo roden, stefan brandys

![text-screen-white](https://user-images.githubusercontent.com/9384/236688877-bd945761-c1b2-4edb-b491-812e0529bc0c.svg)
![text-screen](https://user-images.githubusercontent.com/9384/236688880-fc9fdcfc-201e-4843-bf5a-b17337ac3313.svg)

**Comment by magnum** [comment]
@cirpo  / @fgandellini are we waiting for other logos, or we can go on with these for now?

**Comment by fgandellini** [comment]
@magnum I think we can go with this for now! 👍

**Comment by magnum** [comment]
* any content for the sponsors section?
* levels of sponsorship for paltformatic and the native web?
* do we need to show some empty boxes for available sposorships and/or link the to contact email or similar
* @fgandellini @roberto-contessi i who can take charge of this? i can work on it between today and tomorrow (tuesday) then i have to get back on it by the end of this week or in the weekend... 
cc @cirpo @piccoloaiutante

**Comment by roberto-contessi** [comment]
@magnum  Hi, i can do it tomorrow!

**Comment by cirpo** [comment]
@magnum  

* Our amazing sponsors
* both of them are Platinum
* I would just add something the links to the sponsorship level ("hey do you want to support us? sponsor us!")
* @roberto-contessi is our hero :D (thanks a ton!)

**Comment by magnum** [comment]
@roberto-contessi thank you for the support
i changed some few things and merged

**Comment by cirpo** [comment]
@magnum @roberto-contessi @fgandellini FYI I've added the sponsors logos to figma as well (Page sponsors) https://www.figma.com/file/lUekznwtGCqHDvasC1vrnp/Nodejsconf?type=design&node-id=203-165&t=SX00IBe3qoH9sfP5-0

**Comment by magnum** [comment]
thank you @cirpo 
guys do you think it's better to update the platformatic logo with the one with the name as text too?

**Comment by fgandellini** [comment]
Yes @magnum, better updating it so that we show the company name. I can work on it tomorrow.

**Comment by magnum** [comment]
Thank you @fgandellini
