### ISSUE TITLE
sponsor, spreaker

### ISSUE THREAD

**Issue by magnum** [WEBdeBS/nodejsconf2023#26]
https://cloudhq.net/s/95f597c007a49e

cc @piccoloaiutante @cirpo

**Comment by magnum** [comment]
[spreaker--logos.zip](https://github.com/WEBdeBS/nodejsconf2023/files/11598716/spreaker--logos.zip)

**Comment by fgandellini** [comment]
@magnum I can add this one as well

**Comment by magnum** [comment]
doing it right now :-)
