### ISSUE TITLE
publish first speakers / talks

### ISSUE THREAD

**Issue by magnum** [WEBdeBS/nodejsconf2023#29]
sections' order
- speaker 
- sponsors
- where

**Comment by magnum** [comment]
@cirpo @piccoloaiutante can you confirm the first speakers to publish? 
where can i get the info to publish?
i'll work on on it this evening (mon) or tomorrow (tue)

**Comment by cirpo** [comment]
@magnum tab "selected"[ della cfp](https://docs.google.com/spreadsheets/d/1ztXm6cNqV_Af2aQYNBg0S0896LDimwwzar3YZGlYdgA/edit#gid=1963899149)

grazie


PS. non andare online con le modifiche, stiamo ancora aspettando delle conferme, target date per online Mercoledì 05/07

**Comment by magnum** [comment]
ok @cirpo ! i'll postpone the activities to the next weekend
thank you for the update

**Comment by magnum** [comment]
https://docs.google.com/spreadsheets/d/1Y9Ua4YaCu7TFR6itIm4Btf_3-u7nY12v9dhrKCc5hgA/edit#gid=1806211868

**Comment by magnum** [comment]
i’ll setup the data and structure, after that @roberto-contessi  can you help a graphic touch if needed?

**Comment by roberto-contessi** [comment]
@magnum Yes of course!

**Comment by magnum** [comment]
preview of 1st 4 talks / speakers cc @cirpo @fgandellini 
https://feature-talks--nodejsconf2023.netlify.app/
@roberto-contessi feel free to add you design touch :-)
branch https://github.com/WEBdeBS/nodejsconf2023/tree/feature/talks

**Comment by cirpo** [comment]
that's great @magnum 🙏

I would:
- remove the talk level
- better formatting (no new line and links are not clickable)

**Comment by roberto-contessi** [comment]
@magnum @cirpo Check if it's okay and if you like it! I pushed the commit to the "feature/talk" branch

**Comment by magnum** [comment]
thanks @roberto-contessi 
for me it's ok visually, good job
for me it's ready to be published: @cirpo @fgandellini ?

i've seen the code
https://github.com/WEBdeBS/nodejsconf2023/commit/dec6251907cab58448d93ae5c5b67d6431bcd850
and the only note it's that i'll try to use the original image, maybe with a bw css filter or similar, without the need to remove the background: for the next talks it will be quick if we don't have to open an image editor :-) 

i'll try to convert automatically links in the text to a with href, but we can do it in a next release

**Comment by roberto-contessi** [comment]
@magnum I used this service: www.remove.bg that removes your background in one click. But yes maybe it is still faster to use the original photos

**Comment by fgandellini** [comment]
Hey folks, I'm late to the party here.

I checked the version at https://feature-talks--nodejsconf2023.netlify.app/, and it looks good to me visually.
The only warning I have is the Paolo Insogna bio.
It looks like a copy/paste of Matteo Collina's one, aside from that it's good to go!

About backgrounds, I agree with @magnum, let's keep it simple in case we need last-minute changes.

**Comment by magnum** [comment]
@roberto-contessi 
>I used this service: [www.remove.bg](http://www.remove.bg/) that removes
ok for me to keep this approach if it's so efficient

@fgandellini sorry, in the case it was me :-) i'll fix it right now

@cirpo ok to add a phrase after the last talk, something like
"and more to be come... " or "and more more to be annouced..."
done this and fixed the above, i think we're ready to publish it when you say go :-)

**Comment by cirpo** [comment]
can we add Alex Ruheni as well and then go live?

**Comment by magnum** [comment]
preview here
https://feature-talks--nodejsconf2023.netlify.app/
ready to go?
