### ISSUE TITLE
Figma: create figma card per speaker

### ISSUE THREAD

**Issue by cirpo** [WEBdeBS/nodejsconf2023#35]
We need an image that can be used on socials (twitter/linkedin/facebook) for every speaker

- speaker name
- pic
- talk title
- nodejsconf.it link

**Comment by roberto-contessi** [comment]
@cirpo @magnum I have added on Figma the images for the sponsors, speakers and the conference. 
Tell me if they is ok

**Comment by magnum** [comment]
ok for me... 
@merissimissima?

**Comment by cirpo** [comment]
<3
