### ISSUE TITLE
Figma: create figma card with speakers

### ISSUE THREAD

**Issue by cirpo** [WEBdeBS/nodejsconf2023#37]
We need an image that can be used on socials (twitter/linkedin/facebook) with all the speakers (8 / 9 slots)

**Comment by magnum** [comment]
updates on figma from @roberto-contessi to be confirmed
see https://github.com/WEBdeBS/nodejsconf2023/issues/35
cc @cirpo @merissimissima

**Comment by cirpo** [comment]
<3
