### ISSUE TITLE
Figma: create figma card per sponsor

### ISSUE THREAD

**Issue by cirpo** [WEBdeBS/nodejsconf2023#38]
We need an image that can be used on socials (twitter/linkedin/facebook) per sponsor and with all the sponsors

**Comment by magnum** [comment]
updates on figma from @roberto-contessi to be confirmed
see https://github.com/WEBdeBS/nodejsconf2023/issues/35
cc @cirpo @merissimissima

**Comment by cirpo** [comment]
<3
