### ISSUE TITLE
palmabit and incode as bronze sponsor

### ISSUE THREAD

**Issue by magnum** [WEBdeBS/nodejsconf2023#48]

**Comment by magnum** [comment]
@roberto-contessi can you share palmabit logo? we can add incode and palmabit as bronze sponsor
here's our logo, if you can work on it, otherwise i'll add it in the next days 
cc @cirpo @fgandellini 

![incode-logo-outline-light](https://github.com/WEBdeBS/nodejsconf2023/assets/9384/28a7752c-c4df-4fe2-be3e-656b79034315)
![incode-logo-outline](https://github.com/WEBdeBS/nodejsconf2023/assets/9384/61673550-5c56-4175-b720-c9db459dd00b)

**Comment by roberto-contessi** [comment]
@magnum  Yes, of course! i do now

**Comment by magnum** [comment]
thanks!

**Comment by roberto-contessi** [comment]
@magnum I did the PR, I also fixed the css for mobile

**Comment by magnum** [comment]
if you want you can make our bronze logos smaller, that said, for me it's ok
