### ISSUE TITLE
Update Tamar talk and abstract on the cards (Figma)

### ISSUE THREAD

**Issue by cirpo** [WEBdeBS/nodejsconf2023#52]
Tamar changed title and abstract:

https://docs.google.com/spreadsheets/d/1Y9Ua4YaCu7TFR6itIm4Btf_3-u7nY12v9dhrKCc5hgA/edit?resourcekey#gid=0

**Comment by merissimissima** [comment]
https://www.figma.com/file/lUekznwtGCqHDvasC1vrnp/Nodejsconf?type=design&node-id=371-501&mode=design&t=q4bcVElhFTioeZEc-4
https://www.figma.com/file/lUekznwtGCqHDvasC1vrnp/Nodejsconf?type=design&node-id=371-457&mode=design&t=q4bcVElhFTioeZEc-4
