### ISSUE TITLE
sponsor, sentry

### ISSUE THREAD

**Issue by magnum** [WEBdeBS/nodejsconf2023#54]
from Kamil Ogórek <kamil.ogorek@gmail.com>

> Hey Alessandro,
You can pick and choose any format and size from https://sentry.io/branding/ directly :)
And it should link to https://sentry.io/
Cheers,
Kamil

**Comment by magnum** [comment]
@cirpo which sponsor level?

**Comment by cirpo** [comment]
@magnum Silver
